apiVersion: v1
kind: Secret
metadata:
  name: laravel-secret
  namespace: scoolyn
type: Opaque
data:
  # app-key: base64:your-32-character-secret-key (base64 encoded)
  app-key: YmFzZTY0OnlvdXItMzItY2hhcmFjdGVyLXNlY3JldC1rZXk=